ALTER TABLE `texcludekeywords` CHANGE `cISOSprache` `cISOSprache` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `tkontaktbetreffsprache` CHANGE `cISOSprache` `cISOSprache` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `tkuponsprache` CHANGE `cISOSprache` `cISOSprache` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `tland` CHANGE `cISO` `cISO` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `tlinkgruppesprache` CHANGE `cISOSprache` `cISOSprache` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `tlinksprache` CHANGE `cISOSprache` `cISOSprache` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `tspezialcontentsprache` CHANGE `cISOSprache` `cISOSprache` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `tsprache` CHANGE `cISO` `cISO` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `tsteuerzoneland` CHANGE `cISO` `cISO` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `tversandartsprache` CHANGE `cISOSprache` `cISOSprache` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `tversandzuschlag` CHANGE `cISO` `cISO` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `tversandzuschlagsprache` CHANGE `cISOSprache` `cISOSprache` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `twaehrung` CHANGE `cISO` `cISO` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `tzahlungsartsprache` CHANGE `cISOSprache` `cISOSprache` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `tzahlungseingang` CHANGE `cISO` `cISO` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `tboxsprache` CHANGE `cISO` `cISO` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `tpluginsprachvariablecustomsprache` CHANGE `cISO` `cISO` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `tpluginsprachvariablesprache` CHANGE `cISO` `cISO` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `tsprachiso` CHANGE `cISO` `cISO` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `ttrustedshopskundenbewertung` CHANGE `cISOSprache` `cISOSprache` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `ttrustedshopszertifikat` CHANGE `cISOSprache` `cISOSprache` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
ALTER TABLE `tverpackungsprache` CHANGE `cISOSprache` `cISOSprache` VARCHAR( 5 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL;
UPDATE temailvorlagesprache SET cContentHtml = REPLACE(cContentHtml, '{$Kunde->Anrede}', '{$Kunde->cAnredeLocalized}'), cContentText = REPLACE(cContentText, '{$Kunde->Anrede}', '{$Kunde->cAnredeLocalized}');
INSERT INTO `ttemplateeinstellungen` (`cTemplate`, `cSektion`, `cName`, `cWert`) VALUES('JTL-Shop3-Tiny', 'general', 'use_minify', 'N');