<?php
define("JTLSEARCH_URL_ADMINMENU_VERWALTUNG", $oPlugin->cAdminmenuPfadURL.'verwaltung/');
define("JTLSEARCH_URL_ADMINMENU_VERWALTUNG_TEMPLATES_CSS", JTLSEARCH_URL_ADMINMENU_VERWALTUNG.'templates/css/');
define("JTLSEARCH_URL_ADMINMENU_VERWALTUNG_TEMPLATES_CSS_BASE", JTLSEARCH_URL_ADMINMENU_VERWALTUNG_TEMPLATES_CSS.'verwaltung.css');
