ALTER TABLE  `tkampagnevorgang` ADD INDEX (  `kKampagne` ,  `kKampagneDef` ,  `kKey` );
INSERT INTO `tsprachwerte` (`kSprachISO`, `kSprachsektion`, `cName`, `cWert`, `cStandard`, `bSystem`) VALUES ('1', '1', 'deliverytimeEstimationSimple', '#DELIVERYDAYS# Werktage', '#DELIVERYDAYS# Werktage', '1'), ('2', '1', 'deliverytimeEstimationSimple', '#DELIVERYDAYS# workdays', '#DELIVERYDAYS# workdays', '1');
UPDATE tsprachwerte SET cName = 'cancellationPolicyNotice' WHERE cName = 'cancellationPolicy';
UPDATE tsprachwerte SET cStandard = 'Jetzt bezahlen - sicher und einfach.' WHERE cName = 'orderConfirmationPre' AND kSprachIso=1;
UPDATE tsprachwerte SET cStandard = 'Pay now - safe and easy.' WHERE cName = 'orderConfirmationPre' AND kSprachIso=2;
UPDATE tsprachwerte SET cWert = 'Jetzt bezahlen - sicher und einfach.' WHERE cName = 'orderConfirmationPre' AND kSprachIso=1 AND cWert='Bitte führen Sie den Zahlungsvorgang aus, um Ihre Bestellung abzuschliessen.';
UPDATE tsprachwerte SET cWert = 'Pay now - safe and easy.' WHERE cName = 'orderConfirmationPre' AND kSprachIso=2 AND cWert='Please carry on with the payment process to complete your order.';
ALTER TABLE `tartikel` CHANGE `cHAN` `cHAN` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL;
DELETE FROM `teinstellungenconfwerte` WHERE kEinstellungenConf = 15 and cName = 'Ja, Sicherheitsstufe 1';
INSERT INTO `teinstellungenconfwerte` (`kEinstellungenConf`,`cName`,`cWert`,`nSort`) VALUES (1530,'Ja, Sicherheitsstufe 1','1',2);
INSERT INTO `teinstellungenconfwerte` (`kEinstellungenConf`,`cName`,`cWert`,`nSort`) VALUES(119, 'Keine Variationsaufpreise anzeigen', '0', 3);
INSERT INTO `temailvorlagespracheoriginal` (`kEmailvorlage`, `kSprache`, `cContentHtml`, `cContentText`, `cPDFs`, `cDateiname`) VALUES ('28', '1', '<b>{$Firma->cName}</b><br />{if $Firma->cUnternehmer|strlen>0}{$Firma->cUnternehmer}<br />{/if}{$Firma->cStrasse} {$Firma->cHausnummer}<br />{$Firma->cPLZ} {$Firma->cOrt}<br />{$Firma->cLand}<br />Tel.: {$Firma->cTel}<br />{if $Firma->cFax|strlen>0}Fax.: {$Firma->cFax}<br />{/if}<a href=\"{$Firma->cWWW}\">{$Firma->cWWW}</a><br />{$Firma->cUSTID}<br />', '{$Firma->cName}\n{if $Firma->cUnternehmer|strlen>0}{$Firma->cUnternehmer}\n{/if}{$Firma->cStrasse} {$Firma->cHausnummer}\n{$Firma->cPLZ} {$Firma->cOrt}\n{$Firma->cLand}\nTel.: {$Firma->cTel}\n{if $Firma->cFax|strlen>0}Fax.: {$Firma->cFax}\n{/if}{$Firma->cWWW}\n{$Firma->cUSTID}', '', '');
INSERT INTO `temailvorlagespracheoriginal` (`kEmailvorlage`, `kSprache`, `cContentHtml`, `cContentText`, `cPDFs`, `cDateiname`) VALUES ('28', '2', '<b>{$Firma->cName}</b><br />{if $Firma->cUnternehmer|strlen>0}{$Firma->cUnternehmer}<br />{/if}{$Firma->cStrasse} {$Firma->cHausnummer}<br />{$Firma->cPLZ} {$Firma->cOrt}<br />{$Firma->cLand}<br />Phone: {$Firma->cTel}<br />{if $Firma->cFax|strlen>0}Fax.: {$Firma->cFax}<br />{/if}<a href=\"{$Firma->cWWW}\">{$Firma->cWWW}</a><br />{$Firma->cUSTID}<br />', '{$Firma->cName}\n{if $Firma->cUnternehmer|strlen>0}{$Firma->cUnternehmer}\n{/if}{$Firma->cStrasse} {$Firma->cHausnummer}\n{$Firma->cPLZ} {$Firma->cOrt}\n{$Firma->cLand}\nPhone: {$Firma->cTel}\n{if $Firma->cFax|strlen>0}Fax: {$Firma->cFax}\n{/if}{$Firma->cWWW}\n{$Firma->cUSTID}', '', '');
ALTER TABLE tlink MODIFY kLink int(10) auto_increment;
ALTER TABLE tlinksprache MODIFY kLink int(10);
ALTER TABLE `tnewsletterempfaengerhistory` ADD `cEmailBodyHtml` TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL AFTER `cAktion`, ADD `cRegIp` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL AFTER `cEmailBodyHtml`, ADD `cOptIp` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL AFTER `cRegIp`;
ALTER TABLE `tartikel` ADD `kMassEinheit` INT UNSIGNED NULL AFTER `kVPEEinheit`;
ALTER TABLE `tartikel` ADD `kGrundPreisEinheit` INT UNSIGNED NULL AFTER `kMassEinheit`;
ALTER TABLE `tartikel` ADD `fMassMenge` double NULL AFTER `fArtikelgewicht`;
ALTER TABLE `tartikel` ADD `fGrundpreisMenge` double NULL AFTER `fMassMenge`;
ALTER TABLE `tartikel` ADD `fBreite` double UNSIGNED NULL AFTER `fGrundpreisMenge`;
ALTER TABLE `tartikel` ADD `fHoehe` double UNSIGNED NULL AFTER `fBreite`;
ALTER TABLE `tartikel` ADD `fLaenge` double UNSIGNED NULL AFTER `fHoehe`;
ALTER TABLE `tartikel` ADD `nLiefertageWennAusverkauft` int NULL AFTER `nIstVater`;
ALTER TABLE `tartikel` ADD `nAutomatischeLiefertageberechnung` int NULL AFTER `nLiefertageWennAusverkauft`;
ALTER TABLE `tartikel` ADD `nBearbeitungszeit` int NULL AFTER `nAutomatischeLiefertageberechnung`;
CREATE TABLE IF NOT EXISTS `tmasseinheit` (`kMassEinheit` int(10) unsigned NOT NULL, `cCode` varchar(255) NOT NULL, PRIMARY KEY (`kMassEinheit`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
ALTER TABLE `tmasseinheit` ADD KEY `cCode` (`cCode`);
CREATE TABLE IF NOT EXISTS `tmasseinheitsprache` (`kMassEinheitSprache` int(10) unsigned NOT NULL AUTO_INCREMENT,`kMassEinheit` int(10) unsigned NOT NULL,`kSprache` int(10) unsigned NOT NULL,`cName` varchar(255) NOT NULL, PRIMARY KEY (`kMassEinheitSprache`)) ENGINE=MyISAM DEFAULT CHARSET=latin1;
ALTER TABLE `tmasseinheitsprache` ADD KEY `kMassEinheit` (`kMassEinheit`,`kSprache`);
ALTER TABLE `tcheckboxsprache` CHANGE `cText` `cText` TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL , CHANGE `cBeschreibung` `cBeschreibung` TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
UPDATE `tland` SET `cDeutsch`='Russland' WHERE `cISO`='RU';
INSERT INTO `tsprachwerte` (`kSprachISO`, `kSprachsektion`, `cName`, `cWert`, `cStandard`, `bSystem`) VALUES ('1', '1', 'csrfValidationFailed', 'Die Anfrage konnte nicht verarbeitet werden. Dies kann passieren, wenn die Anfrage von einer unbekannten Quelle gestellt wurde oder die Website-Sitzung zwischenzeitlich abgelaufen ist. Versuchen Sie es bitte erneut.', 'Die Anfrage konnte nicht verarbeitet werden. Dies kann passieren, wenn die Anfrage von einer unbekannten Quelle gestellt wurde oder die Website-Sitzung zwischenzeitlich abgelaufen ist. Versuchen Sie es bitte erneut.', '1');
INSERT INTO `tsprachwerte` (`kSprachISO`, `kSprachsektion`, `cName`, `cWert`, `cStandard`, `bSystem`) VALUES ('2', '1', 'csrfValidationFailed', 'Sorry, your request cannot be processed. The problem may be caused by an expired session or sending your request from an unknown source. Please try again.', 'Sorry, your request cannot be processed. The problem may be caused by an expired session or sending your request from an unknown source. Please try again.', '1');