<?php

define('JTLSEARCH_MANAGER_SERVER_URL', 'https://manager-jtlsearch.jtl-software.de/jtlsearch/manager/index.php');


define("JTLSEARCH_DEBUGGING_LEVEL_CRIT", 1);
define("JTLSEARCH_DEBUGGING_LEVEL_ERROR", 2);
define("JTLSEARCH_DEBUGGING_LEVEL_DEBUG", 3);
define("JTLSEARCH_DEBUGGING_LEVEL_NOTICE", 4);

define("JTLSEARCH_DEBUGGING_MODE_LOG", 1); //In eine lokale Datei debuggen
define("JTLSEARCH_DEBUGGING_MODE_EXTLOG", 2); //In eine externe Datei loggen (JTLSEARCH_DEBUGGING_EXTLOG_URL)
define("JTLSEARCH_DEBUGGING_MODE_ECHO", 3); //Debug-Nachrichten einfach ausgeben
//
// Logging
define("JTLSEARCH_DEBUGGING", true); //Debugging aktiviert?
define("JTLSEARCH_DEBUGGING_LEVEL", 4); //Ab welchem Level soll geloggt werden?
define("JTLSEARCH_DEBUGGING_MODE", 1); //In welchem Mode soll debuggt werden

//Debugging Datei beim lokalen Debugging
define("JTLSEARCH_DEBUGGING_LOG_FILE", PFAD_LOGFILES.'jtlsearchLog.txt');
//URL-Logger
define("JTLSEARCH_DEBUGGING_EXTLOG_URL", "https://proinsel/devshops/jtlsearch/logger/index.php");

// Pfade
define('JTLSEARCH_PFAD', PFAD_ROOT.PFAD_PLUGIN.$oPlugin->cVerzeichnis."/".PFAD_PLUGIN_VERSION.$oPlugin->nVersion."/");

define('JTLSEARCH_PFAD_INCLUDES', JTLSEARCH_PFAD.'includes/');
define('JTLSEARCH_PFAD_CLASSES', JTLSEARCH_PFAD.'classes/');
define('JTLSEARCH_PFAD_ADMINMENU', JTLSEARCH_PFAD.PFAD_PLUGIN_ADMINMENU);
define('JTLSEARCH_PFAD_FRONTEND', JTLSEARCH_PFAD.PFAD_PLUGIN_FRONTEND);
define('JTLSEARCH_PFAD_LIBS', JTLSEARCH_PFAD.'libs/');

define("JTLSEARCH_PFAD_ADMINMENU_TESTPERIOD", JTLSEARCH_PFAD_ADMINMENU . "testperiod/");
define("JTLSEARCH_PFAD_ADMINMENU_TESTPERIOD_INCLUDES", JTLSEARCH_PFAD_ADMINMENU_TESTPERIOD . "includes/");
define("JTLSEARCH_PFAD_ADMINMENU_TESTPERIOD_TEMPLATES", JTLSEARCH_PFAD_ADMINMENU_TESTPERIOD . "templates/");
define("JTLSEARCH_PFAD_ADMINMENU_TESTPERIOD_CLASSES", JTLSEARCH_PFAD_ADMINMENU_TESTPERIOD . "classes/");

define("JTLSEARCH_URL_ADMINMENU_TESTPERIOD_TEMPLATES_CSS", $oPlugin->cAdminmenuPfadURL.'testperiod/templates/css/');
define("JTLSEARCH_URL_ADMINMENU_TESTPERIOD_TEMPLATES_CSS_BASE", JTLSEARCH_URL_ADMINMENU_TESTPERIOD_TEMPLATES_CSS.'base.css');

define("JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG", JTLSEARCH_PFAD_ADMINMENU . "verwaltung/");
define("JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG_INCLUDES", JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG . "includes/");
define("JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG_TEMPLATES", JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG . "templates/");
define("JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG_CLASSES", JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG . "classes/");
define("JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG_MODULES", JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG . "modules/");

define("JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG_EXPORT", JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG_MODULES . "export/");
define("JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG_EXPORT_INCLUDES", JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG_EXPORT . "includes/");
define("JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG_EXPORT_TEMPLATES", JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG_EXPORT . "templates/");
define("JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG_EXPORT_CLASSES", JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG_EXPORT . "classes/");
// CURL Server Pass
define("JTLSEARCH_SECRET_KEY", "5Ce5CSwQfq7JpAhB");

/*
 * Stat types
 */
define("JTLSEARCH_STAT_TYPE_VIEWED", 1);
define("JTLSEARCH_STAT_TYPE_BASKET", 2);
define("JTLSEARCH_STAT_TYPE_RECOMMEND", 3);
define("JTLSEARCH_STAT_TYPE_WISHLIST", 4);
define("JTLSEARCH_STAT_TYPE_DEMAND", 5);
define("JTLSEARCH_STAT_TYPE_NOTIFY", 6);
define("JTLSEARCH_STAT_TYPE_COMPARE", 7);

// Export-Limit pro Run
define("JTLSEARCH_LIMIT_N_METHOD_1", JOBQUEUE_LIMIT_M_EXPORTE);
define("JTLSEARCH_LIMIT_N_METHOD_2", 50);
define("JTLSEARCH_LIMIT_N_METHOD_3", 500);

// Deltaexport
define("JTLSEARCH_DELTAEXPORT_ITEMS_MAX", 500);
define("JTLSEARCH_DELTAEXPORT_TRIGGER_CRON", true);
